### ISSUE TITLE
Trailing semicolons confuse the parser

### ISSUE THREAD

**Issue by nox** [hyperium/mime#102]
Parsing `text/event-stream;` gives a `Mime` value whose subtype is `event-stream;`, that seems wrong to me.

**Comment by nox** [comment]
I just checked and that bug is still present in `master`, I hope the fix will get backported to the 0.3 release though.

**Comment by seanmonstar** [comment]
Yea, this is definitely a bug!

**Comment by seanmonstar** [comment]
Fixed by #103
