### ISSUE TITLE
[Question] mime::Mime constructor from 0.2.6 to current version 

### ISSUE THREAD

**Issue by gbonnema** [hyperium/mime#108]
I am pretty new to both Rust and Mime and I hope you can help me with a small programming issue I have. I am changing an older project to work with 0.3 in stead of 0.2.6, but my understanding of what it is trying to do and how to change is lacking. Could you help me?

This is the code I want to alter:
```
135         // Construct a multipart body
136         let mut multipart = Multipart::new();
-        let content_type = mime::Mime(
-            mime::TopLevel::Application,
-            mime::SubLevel::OctetStream,
-            vec![],
-        );
137         let content_type = mime::APPLICATION_OCTET_STREAM;
138         multipart.add_stream(
139             UPM_UPLOAD_FIELD_NAME,
140             Cursor::new(database_bytes),
141             Some(database_name),
142             Some(content_type),
143         );
144         let mut multipart_prepared = match multipart.prepare() {
145             Ok(p) => p,
146             Err(_) => return Err(UpmError::Sync(String::from("Cannot prepare file upload"))),
147         };
148         let mut multipart_buffer: Vec<u8> = vec![];
149         multipart_prepared.read_to_end(&mut multipart_buffer)?;
150 
151         // Send request
152         let mut response = self.client
153             .post(&url)
154             .basic_auth(self.http_username.clone(), Some(self.http_password.clone()))
155             .header("ContentType", mime::Mime(
156                 mime::TopLevel::Multipart,
157                 mime::SubLevel::FormData,
158                 vec![
159                     (
160                         mime::Attr::Ext(String::from(BOUNDARY_ATTRIBUTE)),
161                         mime::Value::Ext(
162                             String::from(multipart_prepared.boundary()),
163                         )
164                     ),
165                 ],
166             ))
167             .body(multipart_buffer)
168             .send()?;

```

As you can see, line 137 is a replacement, which I could do, because of en ampty vector. However, I am at a loss how to replace the lines 155 - 166.

I tried to figure out how the mime::Mime( ... ) function works, but I couldn't find it (a newbie problem I am afraid). 

Could you point me in the right direction?

Kind regards, Guus Bonnema.

**Comment by seanmonstar** [comment]
In mime 0.3, we moved away from freely constructing Mimes, since the API didn't allow validating that the parameters didn't contain illegal characters (a header value with newlines is a problem!). There are constants for the common ones, but for multipart, with a custom boundary, you'll just need to parse a string into a `Mime`.

```rust
let mime = format!("multipart/form-data; boundary={}", multipart_prepared.boundary())
    .parse::<mime::Mime>()
    .unwrap();
```

------

May I ask what client library you are using? If it is reqwest, it actually had built in multipart support, which can help do more of that for you!

**Comment by gbonnema** [comment]
it is reqwest indeed. I am learning how David Simmons put his program `tupm` together and getting past these errors will help me execute the program and understand how it works.

If you have a multipart translation, I would be grateful.

**Comment by seanmonstar** [comment]
There's a basic example in the docs: https://docs.rs/reqwest/0.9.*/reqwest/struct.RequestBuilder.html#method.multipart

I think in your case, it could look like this:

```rust
use reqwest::multipart;

let part = multipart::Part::bytes(database_bytes)
    .file_name(database_name)
    .mime_str("application/octet-stream")?;

let form = multipart::Form::new()
    .part(UPM_UPLOAD_FIELD_NAME, part);

let resp = self.client
    .post(&url)
    .multipart(form)
    .send()?;
```

Note it might need slight tweaking, since I don't know the types in your example.

**Comment by gbonnema** [comment]
Okee, I finally got the mime issues out of the way. Thank you very much for your support, and I will close this issue now.
