### ISSUE TITLE
build error from crate

### ISSUE THREAD

**Issue by sallyyu0** [hyperium/mime#115]
I'm getting following error today from cargo test. My project does not use mime directly, but some crates I used might have. Any clues?

   Compiling mime_guess v2.0.0
   Compiling mime v0.3.13
error[E0658]: renaming imports with `_` is unstable (see issue #48216)
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/mime_guess-2.0.0/build.rs:120:9
    |
120 |     use std::fmt::Write as _;
    |         ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `mime_guess`.
warning: build failed, waiting for other jobs to finish...
error: build failed

Note: it was ok when for mime_guess v2.0.0-alpha.6.

**Comment by seanmonstar** [comment]
That's the `mime_guess` crate, not `mime`. Though, the error suggests your compiler is older, a new one should work.
