### ISSUE TITLE
Please maintain this

### ISSUE THREAD

**Issue by svenstaro** [hyperium/mime#135]
This crate is an important piece of the Rust ecosystem and I think it could benefit from some additional maintainer love. I realize that everyone is probably very busy and I very much appreciate your work. However, perhaps it might be a good idea to create a call for maintainers and then assigning people permissions to merge PRs and publish new crate versions in order for this crate to live on.

Please don't take this the wrong way. :)

**Comment by est31** [comment]
I've got a response for this question in the hyper repo: https://github.com/hyperium/hyper/issues/2632#issuecomment-905940501

**Comment by matthiasbeyer** [comment]
Yes, please open a call for maintainers!

**Comment by ilka-schulz** [comment]
@seanmonstar Can we please have a call for maintainers?

**Comment by svenstaro** [comment]
@seanmonstar Friendly ping :)

**Comment by seanmonstar** [comment]
Sorry for the lag. I've opened up #153 to track how to move forward with this crate.

**Comment by caneroj1** [comment]
Bumping up this thread on https://github.com/hyperium/mime/issues/153#issuecomment-4588141226
