### ISSUE TITLE
`parse::test_parse_iterator_all_invalid` test fails in mime 0.3.17

### ISSUE THREAD

**Issue by decathorpe** [hyperium/mime#146]
It looks like this test (added recently with https://github.com/hyperium/mime/pull/145 ) fails:

```
failures:
---- parse::test_parse_iterator_all_invalid stdout ----
thread 'parse::test_parse_iterator_all_invalid' panicked at 'called `Result::unwrap_err()` on an `Ok` value: "application/json"', src/parse.rs:452:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    parse::test_parse_iterator_all_invalid

test result: FAILED. 16 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Looking at the source code for the failing test, I'm not sure what it's even supposed to do?

Both values look valid, but the test is called `all_invalid` - and `"application/json"` parses correctly, so there's no error to unwrap.
And even if the `unwrap_err` were changed to `unwrap` in the first assert, the second assert would fail (because `Some(Ok("text/html"))` is not `None`. Maybe this is the result of a copypasta error?

**Comment by 82marbag** [comment]
@decathorpe thank you for reporting and sorry for the unwanted test. It should be now fixed. Let me know if this issue can be closed.

**Comment by decathorpe** [comment]
Thanks! I've disabled the test in Fedora Linux builds of this crate, so there's no need to publish a new release.

But maybe it would be a good idea to add some basic CI to this project? That would have caught this issue early.

**Comment by seanmonstar** [comment]
I think what happened is we do have CI, but it's with Travis, and that got shutdown. So, we need to transition to GH Actions...
