### ISSUE TITLE
#21 breaks mime! / Mime type

### ISSUE THREAD

**Issue by jethrogb** [hyperium/mime#23]
This works in 6fd92cd1, but not in 0451bea from #21:

``` rust
#[macro_use]
extern crate mime;
use mime::*;

pub fn returns_mime() -> Mime {
    mime!(Text/Html;Charset=Utf8)
}
```

In 0451bea you have to write

``` rust
pub fn returns_mime() -> Mime<[(mime::Attr, mime::Value); 1]>
```

which is way too verbose.

This also means you can't build current hyper master with current mime.rs master.

**Comment by jethrogb** [comment]
Nevermind, this appears to be fixed in #21

**Comment by jethrogb** [comment]
So with master, this works, sort of... You need to write this:

```rust
const manual: Mime<[(mime::Attr, mime::Value); 0]> = Mime(TopLevel::Text,SubLevel::Html,[]);
const with_macro: Mime<[(mime::Attr, mime::Value); 1]> = mime!(Text/Html;Charset=Utf8);
```

If you're less verbose, it doesn't work.

**Comment by seanmonstar** [comment]
Yea, this is why I haven't yet published a new version with this change. I'm still thinking how best to expose it. I'd like to have constant mimes, but also not explode the ergonomics.

**Comment by seanmonstar** [comment]
The design is completely different in 0.3, this no longer applies.
