### ISSUE TITLE
from_str doesn't work for wildcards/Star

### ISSUE THREAD

**Issue by Undeterminant** [hyperium/mime#28]
Didn't see an issue tracked for this. Was going to try and fix this this weekend.

**Comment by Undeterminant** [comment]
Related to iron/iron#385.

**Comment by seanmonstar** [comment]
I'm not sure what you mean. Have a test case that fails? It certainly looks like it should work.

**Comment by Undeterminant** [comment]
I was running it on nightly and from_str("*/*") didn't work for me. I'll investigate more.

**Comment by seanmonstar** [comment]
Oh you're right, it doesn't work. The current code follows [this spec's ABNF](http://tools.ietf.org/html/rfc6838#section-4.2), which doesn't allow a `*` character. I suppose some checks before entering that parsing would need to be done to check for things like `*/*`, `anything/*`, etc...

**Comment by Undeterminant** [comment]
It's also documented in hyper [here](http://hyper.rs/hyper/hyper/header/struct.Accept.html).

**Comment by seanmonstar** [comment]
This was fixed in  0.2.3
