### ISSUE TITLE
Serde 0.9

### ISSUE THREAD

**Issue by dbrgn** [hyperium/mime#48]
Any chance to get the `serde` feature updated for serde 0.9?

**Comment by dbrgn** [comment]
I can provide a pull request if it's ok for you. It might break compatibility with serde <0.9 though, I think quite a lot has changed in that release.

**Comment by seanmonstar** [comment]
Yes, it would be, and the next breaking change of the mime crate will see the serde feature removed. It should be done in a separate crate.

**Comment by dbrgn** [comment]
Ok, fair enough. Also, at least serializing is trivial with this generic function:

```rust
fn serialize_to_string<S, T>(val: &T, serializer: S)
        -> Result<S::Ok, S::Error>
        where S: Serializer, T: ToString{
    serializer.serialize_str(&val.to_string())
}
```

It can be used like this:

```rust
#[serde(serialize_with = "serialize_to_string")]
pub mime_type: Mime,
```
