### ISSUE TITLE
Distinguish MIME types from MIME patterns

### ISSUE THREAD

**Issue by kw217** [hyperium/mime#55]
Currently `*/*` can be parsed (per https://github.com/hyperium/mime/issues/28) and printed. This is fine, except that it means it's easy to write code that does nonsensical things like emitting `Content-Type: */*` in an HTTP response.

Would it be possible to have *two* types, one that covers just RFC2045/RFC6838 media types, and a separate one that covers all RFC7231 `media-range`s? Then we could define `struct ContentType( t: MediaType )` and `struct Accept( t: vec![(MediaRange,f32)])`, making it clear what is allowed where.

Maybe for back-compatibility `Mime` could be aliased to `MediaRange`.

**Comment by seanmonstar** [comment]
I can see how having different types would be nice. Does this problem actually happen in practice though? Is there an issue that occurred that made you want this?

**Comment by kw217** [comment]
My colleague is writing an autogenerator, and the input description for one of the endpoints contained a declaration `produces: */*`. The autogenerator turned this into something like
```
let ct = "*/*".parse().unwrap(); 
response.headers.set(ContentType(ct.clone()));
```
I expected this to fail (patterns would need different handling entirely), but instead it succeeded and generated `Content-Type: */*`.

It's not directly causing me problems - all the declarations in our own input have specific media types; the problematic one comes from an external sample - but it surprised me. I'm used to the [Akka/Scala approach](http://doc.akka.io/api/akka-http/current/akka/http/scaladsl/model/index.html), which has separate MediaType and MediaRange types.

**Comment by seanmonstar** [comment]
Having slept on it, I do like it quite a bit. And since all media types are valid ranges, there can be `impl From<MediaType> for MediaRange`.

The concept of quality isn't really specific to media ranges, and in fact are used for several different headers. Things like `Accept-Language`, `Accept-Charset`, `Accept-Encoding`, etc. So, I'd probably leave all mention of quality up the stack, in the `headers` module (of hyper, or wherever if that moves).

**Comment by kw217** [comment]
Great, thanks!

**Comment by seanmonstar** [comment]
I've merged into master a split of the `Mime` type into `MediaType` and `MediaRange`.

**Comment by kw217** [comment]
Cool, thank you!
