### ISSUE TITLE
MIMEs with semicolons after quotes fails to parse

### ISSUE THREAD

**Issue by cpearce** [hyperium/mime#64]
The following panics:

    let s = "video/mp4; codecs=\"a,b\"; width=1024; Height=768; FrameRate=60; BITRATE=100000";
    let m = Mime::from_str(s).unwrap();

with:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromStrError { inner: InvalidToken { pos: 23, byte: 59 } }', /checkout/src/libcore/result.rs:906:4

I'm guessing this is because that mime string has more than one ';' character in it.

YouTube uses MIME types in this format.

**Comment by cpearce** [comment]
Also an example from [RFC 2046](https://tools.ietf.org/html/rfc2046) with multiple semi-colons:

     Content-Type: Message/Partial; number=2; total=3;
                   id="oc=jpbe0M2Yt4s@thumper.bellcore.com"

It would be great if mime crate could handle these types.

**Comment by seanmonstar** [comment]
It's not just multiple semi-colons, but the combination with the quotes, it seems. The test suite does include a successful parse of `text/plain; charset=utf-8; foo=bar` and `text/plain; charset="utf-8"`, but combining them fails. Bug!

**Comment by cpearce** [comment]
Thanks for the quick fix!
