### ISSUE TITLE
Suffix returns none for some types.

### ISSUE THREAD

**Issue by alatiera** [hyperium/mime#70]
Here is my test case.

I constructed the mime-types from content-type http headers I found.

https://play.rust-lang.org/?gist=240a00d7a9e8b949868a9c269cbeca2d&version=stable

**Comment by FuGangqiang** [comment]
I think this is the expected result.

you can check the doc: [mime.suffix](https://docs.rs/mime/0.3.5/mime/struct.Mime.html#method.suffix)

**Comment by alatiera** [comment]
If that's the case, then what's the correct way to get a suffix from content-type header?

**Comment by alatiera** [comment]
After reading [rfc6838](https://tools.ietf.org/html/rfc6838) I see that indeed that's the intended behavior.
But its kinda misleading not having a citation or reference to note that this will work for only the 8 suffixes defined in the [RFC's](https://en.wikipedia.org/wiki/Mime_types#Suffix).

**Comment by seanmonstar** [comment]
I just took a look at your playground link. What would you expect the suffix to be? I only see `audio/ogg` and `audio/mpeg`, neither of which contain a suffix.

**Comment by alatiera** [comment]
At first I thought a suffix was meant to indicate the file-type/extensions since I mainly had encountered +zip/+json/+xml . I guess that's not it.

**Comment by seanmonstar** [comment]
Ah, you may be interested in the [mime_guess](https://crates.io/crates/mime_guess) crate.
