### ISSUE TITLE
Serde feature?

### ISSUE THREAD

**Issue by matthiasbeyer** [hyperium/mime#76]
Hi,

would it be appropriate to make the `Mime` type `Deserialize` and `Serialize` (possibly behind a feature gate)?

I would like to use that in one of my projects and implementing it myself seems to be possible, but if others could use that it would be better to do it here in this crate, I suppose?

**Comment by seanmonstar** [comment]
I know quite a few crates include that, but I've never personally liked that. It'd be another public dependency that upgrading could mean breaking changes (I realize serde is 1.0 and trying to be stable).

I think it'd be pretty easy to wrap over mime anyways, since it serializes to a string.

**Comment by novacrazy** [comment]
I feel like I should mention here that the serde implementation in #84 is simple enough that either this library or serde would have to change quite drastically for it to be significantly difficult to upgrade.

**Comment by seanmonstar** [comment]
With the ability to depend on different versions of the same crate optionally (added in Rust 1.31), I've added this to master. It'd be usable (when 0.4 is published) like this:

```toml
[dependencies]
mime = { version = "0.4", features = ["serde1"] }
```

**Comment by matthiasbeyer** [comment]
Well... about time to publish "0.4", isn't it? :laughing:
