### ISSUE TITLE
No way to create a custom Name value?

### ISSUE THREAD

**Issue by netvl** [hyperium/mime#77]
It looks like that there is no way to construct a custom `Name` value without going through `Mime::from_str`. It is only possible to use predefined ones, like `mime::TEXT` or `mime::HTML`. This is quite inconvenient if there is a need to work with `type_()` and `subtype()` methods. For example, I would like to check whether the given `Mime`s subtype is `xhtml` (as in `application/xhtml+xml`) in a generic match context, like this:
```rust
let XHTML = ???;  // "xhtml"
match mime.subtype() {
    mime::HTML => "html",
    XHTML => "xhtml",
    mime::JPEG => "jpg",
    mime::PNG => "png",
    mime::GIF => "gif",
    _ => "unknown"
}
```
but there is simply no way to do it.

IMO, ideally there should be a way to define `const` values of `Name` and `Mime` types, precisely for use cases like this. At the moment, the constants provided by the library feel "blessed" somehow, compared to custom values which users of the library would potentially like to create.

**Comment by netvl** [comment]
That said, the last example can be rewritten as
```rust
match mime.subtype() {
    ...
    st if st.as_str() == "xhtml" => "xhtml",
    ...
}
``` 
but this approach does not feel right at all.

**Comment by seanmonstar** [comment]
This seems like it was probably just an oversight! There should probably be a `FromStr` implementation for `Name` to allow creating new ones.

**Comment by SimonSapin** [comment]
Even with `FromStr` you’d still need to use an `if` guard in that match expression, since `let` bindings cannot be referenced in pattern position. `const`s can, but you’d need a `const fn` constructor. Even after miri lands and if it can run a parsing algorithm, `const` in patterns do structural matching rather than using `PartialEq`.

**Comment by netvl** [comment]
@SimonSapin 

> since let bindings cannot be referenced in pattern position

Strange, I thought it was possible and that I did this some time ago... probably I'm mistaken. One more reason to allow defining `Name`s as `const`s.
