### ISSUE TITLE
Cannot create mimes with plus in mimes! macro

### ISSUE THREAD

**Issue by mqzry** [hyperium/mime#80]
I tried to add
`IMAGE_SVG, "image/svg+xml", 5, Some(9);`

But I get syntax errors. How should I pass the plus option parameter? Am I doing something wrong?

**Comment by kaj** [comment]
I had the same problem and fixed it by changing the `mimes` macro in #86 .

**Comment by kaj** [comment]
I guess this issue can be closed now that #86 is merged?

**Comment by seanmonstar** [comment]
@kaj thanks! (btw, just published 0.3.8 with the svg constant).
