### ISSUE TITLE
Add APPLICATION_JAVASCRIPT as a common type

### ISSUE THREAD

**Issue by colinbankier** [hyperium/mime#81]
According to https://tools.ietf.org/html/rfc4329, "application/javascript" is preferred over "text/javascript".
It would seem handy to have this as a common type / constant.

**Comment by Jim-Holmstroem** [comment]
Added as a constant in https://github.com/hyperium/mime/pull/82

**Comment by sanmai-NL** [comment]
@colinbankier: this can be closed now.

**Comment by colinbankier** [comment]
Great, thanks :+1:
