### ISSUE TITLE
mime 0.3.10 is backwards incompatible and published

### ISSUE THREAD

**Issue by richardwhiuk** [hyperium/mime#93]
mime 0.3.10 was published < an hour ago (https://crates.io/crates/mime), and has merged https://github.com/hyperium/mime/commit/62c82fd6a0f134a2f0c5d57a8f46111d4597a8a3 was not backwards compatible.

This seems to have been noted (https://github.com/hyperium/mime/commit/62c82fd6a0f134a2f0c5d57a8f46111d4597a8a3#diff-80398c5faae3c069e4e6aa2ed11b28c0R12) but the publish appears to have happened anyway.

This is causing builds of reqwest to fail - namely https://github.com/seanmonstar/reqwest/blob/v0.9.2/src/response.rs#L211-L218 with the following:

```
   Compiling mime v0.3.10
...
   Compiling reqwest v0.9.2
error[E0599]: no method named `as_str` found for type `mime::Value<'_>` in the current scope
   --> /opt/rust/registry/src/github.com-1ecc6299db9ec823/reqwest-0.9.2/src/response.rs:216:44
    |
216 |                     .map(|charset| charset.as_str())
    |                                            ^^^^^^

error: aborting due to previous error
```

**Comment by seanmonstar** [comment]
Yep, a mistake in a rebase, just published 0.3.11 that is fixed up. :cry:
